### ISSUE TITLE
A possible problem

### ISSUE THREAD

**Issue by shlyakpavel** [neosmart/CppSQLite#8]
https://github.com/neosmart/CppSQLite/blob/b53922ee1933f1e800b0eaaea55078bfbad1a056/CppSQLite3.cpp#L68-L80
Is it possible that mpBuf is null at that point? Is passing it to memcpy safe enough?

**Comment by mqudsi** [comment]
```cpp
if (!mpBuf && mnBufferLen > 0)
```

may be rewritten as 

```cpp
if (mpBuf == null && mnBufferLen > 0)
```

Per De Morgan's law, that means the only way line 78 can be reached (the negation of a conjunction) is the following (the disjunction of the negation):

```cpp
assert(mpBuf != null || mnBufferLen <= 0)
std::memcpy(...);
```

It is safe (even if ill-advised) to pass an invalid pointer to `std::memcpy(...)` as the destination **if** the length is zero, the only catch is that as you can see, `mpBuf` may be null if `mnBufferLen` is **less than** or equal to 0. [`mnBufferLen` is signed](https://github.com/neosmart/CppSQLite/blob/b53922ee1933f1e800b0eaaea55078bfbad1a056/CppSQLite3.h#L56) so it's *theoretically* possible that it contains a negative value, but `std::memcpy` takes an *unsigned* `size_t` length parameter, which would result in a negative value being interpreted as a very large one, which would in fact result in an invalid `memcpy` call.

The only question that remains is if mnBufferLen could possibly be negative in the first place. It's a private variable that's only modified in a few places, but it does sometimes obtain values derived from user-provided arguments, such as here:

https://github.com/neosmart/CppSQLite/blob/b53922ee1933f1e800b0eaaea55078bfbad1a056/CppSQLite3.cpp#L311

or if you pass in a string longer than 2GiB but less than 4GiB, `strlen` will return a positive unsigned number that will be coerced to a negative signed int assigned to `mnBufferLen` below, which *may* if allocation succeeds bypass the subsequent null check:

https://github.com/neosmart/CppSQLite/blob/b53922ee1933f1e800b0eaaea55078bfbad1a056/CppSQLite3.cpp#L247-L265

So the code is absolutely not safe and may in fact crash, but realistically, if it's doing so that means that you probably have a bug somewhere else in your code that is triggering the crash. The entire codebase is like that, it's very early 2000s in its design and lack of respect for signed types and it would take a full rewrite to address them all. But in terms of whether using the library the right way could still result in unsafe memory access, the answer should still be no.

Note that the following code looks like it could possibly result in `mnBufferLen` being negative if `strlen()` returns a negative value (it actually returns a signed

**Comment by shlyakpavel** [comment]
@mqudsi thank you for a nice explanation!

**Comment by mqudsi** [comment]
No problem. Good luck hunting down your issue.
